### PR TITLE
acomms, linebasedcomms: remove deprecated boost io_service code

### LINKED ISSUE #103: boost 1.70 has removed get_io_service
```
[80/228] Building CXX object src/CMakeFiles/goby.dir/acomms/modemdriver/driver_base.cpp.o
FAILED: src/CMakeFiles/goby.dir/acomms/modemdriver/driver_base.cpp.o 
/usr/bin/c++  -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H -DBOOST_ALL_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DHAS_GMP -DSHARED_LIBRARY_SUFFIX=\".so\" -Dgoby_EXPORTS -Iinclude -Iinclude/goby/protobuf -Iinclude/goby/acomms/protobuf -Iinclude/goby/util/protobuf -Iinclude/goby/middleware/protobuf -I/usr/lib/cmake/MOOS/../../../include -Os -fomit-frame-pointer -O3 -DNDEBUG -fPIC   -Wno-misleading-indentation -std=gnu++14 -MD -MT src/CMakeFiles/goby.dir/acomms/modemdriver/driver_base.cpp.o -MF src/CMakeFiles/goby.dir/acomms/modemdriver/driver_base.cpp.o.d -o src/CMakeFiles/goby.dir/acomms/modemdriver/driver_base.cpp.o -c ../src/acomms/modemdriver/driver_base.cpp
In file included from include/goby/util/linebasedcomms.h:34,
                 from ../src/acomms/modemdriver/driver_base.h:32,
                 from ../src/acomms/modemdriver/driver_base.cpp:28:
include/goby/util/linebasedcomms/tcp_server.h: In member function 'void goby::util::TCPConnection::start()':
include/goby/util/linebasedcomms/tcp_server.h:108:28: error: 'boost::asio::ip::tcp::socket' {aka 'class boost::asio::basic_stream_socket<boost::asio::ip::tcp>'} has no member named 'get_io_service'
  108 |     void start() { socket_.get_io_service().post(boost::bind(&TCPConnection::read_start, this)); }
      |                            ^~~~~~~~~~~~~~
include/goby/util/linebasedcomms/tcp_server.h: In member function 'void goby::util::TCPConnection::write(const goby::util::protobuf::Datagram&)':
include/goby/util/linebasedcomms/tcp_server.h:112:17: error: 'boost::asio::ip::tcp::socket' {aka 'class boost::asio::basic_stream_socket<boost::asio::ip::tcp>'} has no member named 'get_io_service'
  112 |         socket_.get_io_service().post(boost::bind(&TCPConnection::socket_write, this, msg));
      |                 ^~~~~~~~~~~~~~
include/goby/util/linebasedcomms/tcp_server.h: In member function 'void goby::util::TCPConnection::close(const boost::system::error_code&)':
include/goby/util/linebasedcomms/tcp_server.h:117:17: error: 'boost::asio::ip::tcp::socket' {aka 'class boost::asio::basic_stream_socket<boost::asio::ip::tcp>'} has no member named 'get_io_service'
  117 |         socket_.get_io_service().post(boost::bind(&TCPConnection::socket_close, this, error));
      |                 ^~~~~~~~~~~~~~
```

According to boost asio changelog (https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/history.html)

> Note: One potential source of breakage in existing user code is when reusing an I/O object's io_context for constructing another I/O object, as in:
> 
> asio::steady_timer my_timer(my_socket.get_executor().context());

and

>  The previously deprecated get_io_context and get_io_service member functions have now been removed.

### PR DESCRIPTION
**Pull request by russkel**
Please note this is entirely untested code. This now compiles (at least on Alpine Linux edge) with latest version of boost (1.71).

Fixes #103 .

### CODE REVIEW

**Comment by russkel** [comment]
Hmm, so it seems executors were only recently introduced in boost (1.66) hence all the tests failing.

**Comment by tsaubergine** [comment]
How frustrating. Looks like we might have to do some #if work based on the Boost version.

**Comment by russkel** [comment]
Yeah it does look like that. Also do the test cases cover these parts of the code?

**Comment by tsaubergine** [comment]
No they don't unfortunately.

**Comment by tsaubergine** [comment]
Could you please also sign (add your name, date, email) to the CLA agreement in https://github.com/GobySoft/goby3/blob/3.0/AUTHORS and push to this branch? I missed asking you to do this on your first PR. Thanks!

**Comment by tsaubergine** [comment]
This seems to be the rationale for the change: https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/net_ts.html

We either need some significant #if work based on the Boost version, or use #define BOOST_ASIO_ENABLE_OLD_SERVICES. The latter is my preference for now I think, given how many places io_service is used in the code.

**Comment by russkel** [comment]
I did not know of the existence of BOOST_ASIO_ENABLE_OLD_SERVICES. I will attempt using this when updating my goby package to latest beta.

**Comment by russkel** [comment]
I have just attempted to compile with boost 1.71 and that compiler define does not work. It would have been nice if it was that simple :cry:

**Comment by russkel** [comment]
I believe this is now fixed in https://github.com/GobySoft/goby3/commit/997168adfed8147d7ca933d05cb9dc7363f5e797

**Pull request closed without merging**
