### PR TITLE
Micromodem 2 improvements - multi-message reply support and optional query all cfg

### PR DESCRIPTION
**Pull request by russkel**
Fixes the issues I ran into in #126 

- Added a configuration parameter to make query_all optional, set to default true
- I added state and timeout when receiving a multi message reply.

Our utilities now work well with MM2 firmware, and are well behaved and wait for all the CFG messages to come in before carrying on.

Something things to note:
- I added a last_keepalive_received to the receive handler. I noticed the keepalive messages were being sent at inopportune times and this would prevent this from happening.

### CODE REVIEW

**Comment by tsaubergine** [comment]
Thanks for this. 
Yeah I should convert everything in this driver to use the new std::chrono based stuff for time.

Here's what it looks like for your change:
[patch.txt](https://github.com/GobySoft/goby3/files/3950432/patch.txt)

If you want to do the same for the rest of the time handling in this driver, I would appreciate it.

**Comment by russkel** [comment]
> If you want to do the same for the rest of the time handling in this driver, I would appreciate it.

Throw it up as a TODO issue and I might get around to it when I get a moment.

Thanks for the patch, FYI you have write access to the PR repo as you are a maintainer.

**Comment by tsaubergine** [comment]
I updated the rest of the non-date time handling in the driver to use std::chrono (for now dates will still use boost::posix_time until switching to C++20... a few years off still probably).

This seems to work well for both MicroModem 1 and 2 for my tests. 

Thanks for this!

**Comment by russkel** [comment]
Great to hear. Thanks for merging.

**Pull request merged**
